"""create initial schema

Revision ID: 70cec280aa2f
Revises:
Create Date: 2026-10-09 17:16:52.988660

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "70cec280aa2f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

auth_method = postgresql.ENUM("LOCAL", "GOOGLE", name="auth_method")
exercise_scope = postgresql.ENUM("PRIVATE", "GLOBAL", name="exercise_scope")
exercise_version_status = postgresql.ENUM(
    "PENDING", "APPROVED", name="exercise_version_status"
)
trainer_exercise_status = postgresql.ENUM(
    "ACTIVE", "INACTIVE", "HIDDEN", name="trainer_exercise_status"
)
catalog_visibility = postgresql.ENUM(
    "LOCAL", "PENDING", "GLOBAL", name="catalog_visibility"
)


def upgrade() -> None:
    """Upgrade schema."""
    auth_method.create(op.get_bind(), checkfirst=True)
    exercise_scope.create(op.get_bind(), checkfirst=True)
    exercise_version_status.create(op.get_bind(), checkfirst=True)
    trainer_exercise_status.create(op.get_bind(), checkfirst=True)
    catalog_visibility.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_segments",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "auth_method",
            postgresql.ENUM("LOCAL", "GOOGLE", name="auth_method", create_type=False),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("oauth_subject", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(auth_method = 'LOCAL' AND password_hash IS NOT NULL) OR (auth_method = 'GOOGLE' AND oauth_subject IS NOT NULL)",
            name="ck_users_auth_method_credentials",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("oauth_subject"),
    )
    op.create_table(
        "equipment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "visibility",
            postgresql.ENUM(
                "LOCAL",
                "PENDING",
                "GLOBAL",
                name="catalog_visibility",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_equipment_global_name_ci",
        "equipment",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("visibility = 'GLOBAL'"),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "scope",
            postgresql.ENUM(
                "PRIVATE", "GLOBAL", name="exercise_scope", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("latest_approved_version_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["latest_approved_version_id"],
            ["exercise_versions.id"],
            name="fk_exercises_latest_approved_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "training_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "duration_minutes > 0", name="ck_training_groups_duration_minutes"
        ),
        sa.CheckConstraint("max_age >= min_age", name="ck_training_groups_age_range"),
        sa.CheckConstraint("min_age > 0", name="ck_training_groups_min_age"),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "visibility",
            postgresql.ENUM(
                "LOCAL",
                "PENDING",
                "GLOBAL",
                name="catalog_visibility",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_training_types_global_name_ci",
        "training_types",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("visibility = 'GLOBAL'"),
    )
    op.create_table(
        "exercise_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "APPROVED", name="exercise_version_status", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column("min_participants", sa.Integer(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "duration_minutes > 0", name="ck_exercise_versions_duration_minutes"
        ),
        sa.CheckConstraint("max_age >= min_age", name="ck_exercise_versions_age_range"),
        sa.CheckConstraint(
            "max_participants >= min_participants",
            name="ck_exercise_versions_participant_range",
        ),
        sa.CheckConstraint("min_age > 0", name="ck_exercise_versions_min_age"),
        sa.CheckConstraint(
            "min_participants > 0", name="ck_exercise_versions_min_participants"
        ),
        sa.CheckConstraint(
            "version_number > 0", name="ck_exercise_versions_version_number"
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exercise_id", "version_number"),
    )
    op.create_index(
        "uq_exercise_versions_pending",
        "exercise_versions",
        ["exercise_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "training_group_schema_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("training_group_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.SmallInteger(), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("percentage <= 100", name="ck_schema_items_percentage_max"),
        sa.CheckConstraint(
            "percentage > 0", name="ck_schema_items_percentage_positive"
        ),
        sa.CheckConstraint("position > 0", name="ck_schema_items_position"),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["training_segments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_group_id"],
            ["training_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("training_group_id", "position"),
    )
    op.create_table(
        "training_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("training_group_id", sa.UUID(), nullable=False),
        sa.Column("participant_count", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("group_name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("group_min_age_snapshot", sa.Integer(), nullable=False),
        sa.Column("group_max_age_snapshot", sa.Integer(), nullable=False),
        sa.Column("training_duration_snapshot", sa.Integer(), nullable=False),
        sa.Column(
            "available_equipment_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "training_types_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "schema_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "participant_count > 0", name="ck_training_plans_participant_count"
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_group_id"],
            ["training_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_version_equipment",
        sa.Column("exercise_version_id", sa.UUID(), nullable=False),
        sa.Column("equipment_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_version_id"],
            ["exercise_versions.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_version_id", "equipment_id"),
    )
    op.create_table(
        "exercise_version_segments",
        sa.Column("exercise_version_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_version_id"],
            ["exercise_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["training_segments.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_version_id", "segment_id"),
    )
    op.create_table(
        "exercise_version_training_types",
        sa.Column("exercise_version_id", sa.UUID(), nullable=False),
        sa.Column("training_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_version_id"],
            ["exercise_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_type_id"],
            ["training_types.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_version_id", "training_type_id"),
    )
    op.create_table(
        "trainer_exercises",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("trainer_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE",
                "INACTIVE",
                "HIDDEN",
                name="trainer_exercise_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("min_age", sa.Integer(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column("min_participants", sa.Integer(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "duration_minutes > 0", name="ck_trainer_exercises_duration_minutes"
        ),
        sa.CheckConstraint("max_age >= min_age", name="ck_trainer_exercises_age_range"),
        sa.CheckConstraint(
            "max_participants >= min_participants",
            name="ck_trainer_exercises_participant_range",
        ),
        sa.CheckConstraint("min_age > 0", name="ck_trainer_exercises_min_age"),
        sa.CheckConstraint(
            "min_participants > 0", name="ck_trainer_exercises_min_participants"
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["exercise_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trainer_id", "exercise_id"),
    )
    op.create_table(
        "trainer_exercise_equipment",
        sa.Column("trainer_exercise_id", sa.UUID(), nullable=False),
        sa.Column("equipment_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_exercise_id"],
            ["trainer_exercises.id"],
        ),
        sa.PrimaryKeyConstraint("trainer_exercise_id", "equipment_id"),
    )
    op.create_table(
        "trainer_exercise_segments",
        sa.Column("trainer_exercise_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["training_segments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_exercise_id"],
            ["trainer_exercises.id"],
        ),
        sa.PrimaryKeyConstraint("trainer_exercise_id", "segment_id"),
    )
    op.create_table(
        "trainer_exercise_training_types",
        sa.Column("trainer_exercise_id", sa.UUID(), nullable=False),
        sa.Column("training_type_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trainer_exercise_id"],
            ["trainer_exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_type_id"],
            ["training_types.id"],
        ),
        sa.PrimaryKeyConstraint("trainer_exercise_id", "training_type_id"),
    )
    op.create_table(
        "training_plan_exercises",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("training_plan_id", sa.UUID(), nullable=False),
        sa.Column("trainer_exercise_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("exercise_version_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("schema_position", sa.Integer(), nullable=False),
        sa.Column("name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("description_snapshot", sa.Text(), nullable=False),
        sa.Column("min_age_snapshot", sa.Integer(), nullable=False),
        sa.Column("max_age_snapshot", sa.Integer(), nullable=False),
        sa.Column("min_participants_snapshot", sa.Integer(), nullable=False),
        sa.Column("max_participants_snapshot", sa.Integer(), nullable=False),
        sa.Column("duration_minutes_snapshot", sa.Integer(), nullable=False),
        sa.Column(
            "equipment_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "training_types_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "segments_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "duration_minutes_snapshot > 0", name="ck_plan_exercises_duration_minutes"
        ),
        sa.CheckConstraint("position > 0", name="ck_plan_exercises_position"),
        sa.CheckConstraint(
            "schema_position > 0", name="ck_plan_exercises_schema_position"
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_version_id"],
            ["exercise_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_exercise_id"],
            ["trainer_exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_plan_id"],
            ["training_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("training_plan_id", "position"),
    )
    # ### end Alembic commands ###
    op.create_foreign_key(
        "fk_exercises_latest_approved_version",
        "exercises",
        "exercise_versions",
        ["latest_approved_version_id"],
        ["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "fk_exercises_latest_approved_version",
        "exercises",
        type_="foreignkey",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_plan_exercises")
    op.drop_table("trainer_exercise_training_types")
    op.drop_table("trainer_exercise_segments")
    op.drop_table("trainer_exercise_equipment")
    op.drop_table("trainer_exercises")
    op.drop_table("exercise_version_training_types")
    op.drop_table("exercise_version_segments")
    op.drop_table("exercise_version_equipment")
    op.drop_table("training_plans")
    op.drop_table("training_group_schema_items")
    op.drop_index(
        "uq_exercise_versions_pending",
        table_name="exercise_versions",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("exercise_versions")
    op.drop_index(
        "uq_training_types_global_name_ci",
        table_name="training_types",
        postgresql_where=sa.text("visibility = 'GLOBAL'"),
    )
    op.drop_table("training_types")
    op.drop_table("training_groups")
    op.drop_table("refresh_tokens")
    op.drop_table("exercises")
    op.drop_index(
        "uq_equipment_global_name_ci",
        table_name="equipment",
        postgresql_where=sa.text("visibility = 'GLOBAL'"),
    )
    op.drop_table("equipment")
    op.drop_table("users")
    op.drop_table("training_segments")
    # ### end Alembic commands ###
    catalog_visibility.drop(op.get_bind(), checkfirst=True)
    trainer_exercise_status.drop(op.get_bind(), checkfirst=True)
    exercise_version_status.drop(op.get_bind(), checkfirst=True)
    exercise_scope.drop(op.get_bind(), checkfirst=True)
    auth_method.drop(op.get_bind(), checkfirst=True)
